'use client';
import { useEffect,useRef,useState } from 'react';
import { usePathname,useRouter } from 'next/navigation';
import { questions } from '@/lib/questions';
import { clearSession,getSession,saveSession } from '@/lib/store';
import type { ExamSession,ProctorEvent } from '@/lib/exam';
import Exam from '@/components/Exam';
import DemoLogin from '@/components/DemoLogin';
import { PASSING_SCORE } from '@/lib/exam';
import PreExamVerification from '@/components/PreExamVerification';

const candidate={name:'testcandidate',application:'DEMO-LL-2026-001',licence:"Learner's Licence",state:'Maharashtra'};
const steps=['Login','Device check','Verification','Instructions','Examination'];
function Shell({children}:{children:React.ReactNode}){return <><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="/" className="font-bold text-blue-800">LL <span className="text-slate-700">Proctor</span></a><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">DEMO ENVIRONMENT</span></div></header>{children}<footer className="mx-auto max-w-6xl px-5 py-6 text-xs text-slate-500">Hackathon prototype — government services and candidate data are simulated.</footer></>}
function Camera({onStream}:{onStream?:(ok:boolean)=>void}){const video=useRef<HTMLVideoElement>(null);const [message,setMessage]=useState('Camera preview is ready when you allow access.'); const stream=useRef<MediaStream>(); const start=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error();stream.current=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(video.current)video.current.srcObject=stream.current;setMessage('Camera and microphone connected');onStream?.(true)}catch{setMessage('Camera access is blocked. Allow access in your browser and try again.');onStream?.(false)}};useEffect(()=>{start();return()=>stream.current?.getTracks().forEach(t=>t.stop())},[]);return <div className="card overflow-hidden"><div className="aspect-video bg-slate-900"><video ref={video} autoPlay muted playsInline className="h-full w-full object-cover"/></div><div className="p-3"><p className="text-sm font-semibold">{message}</p><button onClick={start} className="mt-2 text-sm font-bold text-blue-700">Try camera again</button></div></div>}
function Status({icon='✓',children,good=true}:{icon?:string;children:React.ReactNode;good?:boolean}){return <div className={`flex gap-3 rounded-xl p-3 ${good?'bg-emerald-50 text-emerald-950':'bg-amber-50 text-amber-950'}`}><span className="font-bold">{icon}</span><span className="text-sm font-medium">{children}</span></div>}
function Instructions({onStart}:{onStart:()=>void}){const [agreed,setAgreed]=useState(false);return <main className="mx-auto max-w-3xl px-5 py-10"><div className="card p-7"><h1 className="text-3xl font-bold">Proctoring instructions</h1><div className="mt-6 space-y-4 text-slate-700 text-sm"><p>Please read and acknowledge the following rules before starting your examination:</p><ul className="list-disc pl-5 space-y-2"><li>Keep your face clearly visible in the camera throughout the test.</li><li>Keep your eyes focused on the test screen.</li><li>Do not repeatedly look around or away from the screen.</li><li>Do not use your phone, notes, books, or other unauthorized materials.</li><li>Do not communicate with another person during the test.</li><li>Avoid unnecessary background noise or suspicious audio activity.</li><li>Do not attempt to switch tabs/windows or leave the test environment.</li><li>Follow all test and proctoring rules throughout the session.</li><li><b>I understand that repeated suspicious activity can result in warnings and that 5 warnings will automatically terminate my test.</b></li></ul><div className="mt-6 pt-5 border-t border-slate-200"><label className="flex items-start gap-3 cursor-pointer"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="mt-0.5 h-5 w-5 rounded border-slate-300 text-blue-600 focus:ring-blue-600"/><span className="font-semibold text-slate-900 select-none">I acknowledge and agree to follow all proctoring instructions and rules.</span></label></div></div><button disabled={!agreed} onClick={onStart} className="btn-primary mt-7 w-full sm:w-auto px-8">I Understand &amp; Continue</button></div></main>}
export default function App(){const path=usePathname(),router=useRouter();const [device,setDevice]=useState<'checking'|'ready'|'issue'>('checking'); const [session,setSession]=useState<ExamSession|null>(null); const [now,setNow]=useState(Date.now());const [offline,setOffline]=useState(false);const [paused,setPaused]=useState(false);const [showRecovery,setShowRecovery]=useState(false);
useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);useEffect(()=>{getSession().then(s=>{if(s)setSession(s)});const lost=()=>setOffline(true), back=()=>setOffline(false);window.addEventListener('offline',lost);window.addEventListener('online',back);return()=>{window.removeEventListener('offline',lost);window.removeEventListener('online',back)}},[]);
const navigate=(x:string)=>router.push(x);const addEvent=(type:string,severity:ProctorEvent['severity']='warning')=>{if(!session)return;const n={...session,events:[...session.events,{id:crypto.randomUUID(),type,timestamp:new Date().toISOString(),severity,resolved:false}]};setSession(n);saveSession(n)};const startExam=()=>{const startedAt=Date.now();const n:ExamSession={id:crypto.randomUUID(),status:'EXAM_RUNNING',startedAt,durationMs:20*60*1000,questionStartedAt:startedAt,answers:{},events:[],sync:'synced',questionIndex:0};setSession(n);saveSession(n);navigate('/exam')};
const content=()=>{if(path==='/')return <main className="mx-auto max-w-6xl px-5 py-14"><div className="grid gap-10 md:grid-cols-2 md:items-center"><div><p className="font-bold text-blue-700">ONLINE LEARNER'S LICENCE EXAMINATION</p><h1 className="mt-3 text-5xl font-extrabold tracking-tight text-slate-900">Learner&apos;s Licence Test</h1><p className="mt-5 max-w-xl text-xl leading-8 text-slate-600">A simple and reliable way to complete your online learner&apos;s licence examination.</p><button onClick={()=>navigate('/login')} className="btn-primary mt-8">Start Test</button></div><div className="card p-6"><h2 className="text-xl font-bold">Before you begin</h2><div className="mt-5 space-y-3"><Status>Camera and microphone required</Status><Status>Use a stable internet connection</Status><Status>Keep your face visible during the examination</Status><Status icon="i" good={false}>This is a safe practice demo, not an official test.</Status></div></div></div></main>;
if(path==='/login')return <DemoLogin onSuccess={()=>navigate('/setup')}/>;
if(path==='/setup')return <main className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-bold">Preparing your test</h1><p className="mt-2 text-slate-600">We check your device before the exam so interruptions are less likely.</p><div className="card mt-6 p-6"><Camera onStream={ok=>setDevice(ok?'ready':'issue')}/><div className="mt-5 space-y-3">{['Device and browser','Camera','Microphone','Internet','Face detection readiness','Fullscreen capability'].map((x,i)=><Status key={x} icon={device==='checking'&&i<3?'…':device==='issue'&&i===1?'⚠':'✓'} good={!(device==='issue'&&i===1)}>{x} {device==='checking'&&i<3?'— checking…':device==='issue'&&i===1?'— needs permission':'— ready'}</Status>)}</div><button disabled={device==='checking'} onClick={()=>navigate('/verification')} className="btn-primary mt-6">Continue</button></div></main>;
if(path==='/verification')return <PreExamVerification onComplete={()=>navigate('/instructions')}/>;
if(path==='/instructions')return <Instructions onStart={startExam}/>;
if(path==='/exam')return <Exam session={session} setSession={setSession} now={now} offline={offline} setOffline={setOffline} addEvent={addEvent} finish={()=>navigate('/result')}/>;
if(path==='/result') {const correct=session?questions.filter(q=>session.answers[q.id]===q.correctAnswer).length:0;const passed=session?.result==='PASS'||correct>=PASSING_SCORE;return <main className="mx-auto max-w-2xl px-5 py-10"><div className="card p-8 text-center"><p className={`font-bold ${passed?'text-emerald-700':'text-red-700'}`}>EXAM RESULT</p><h1 className={`mt-3 text-4xl font-extrabold ${passed?'text-emerald-700':'text-red-700'}`}>Status: {passed?'PASSED (Cleared Exam)':'FAILED (Failed Test)'}</h1><p className="mt-5 text-2xl font-extrabold text-slate-900">Final Score: {correct} / {questions.length}</p><p className="mt-1 text-sm font-semibold text-slate-500">Passing Requirement: {PASSING_SCORE} / {questions.length}</p><p className="mt-1 text-sm text-slate-600">Candidate: testcandidate</p><p className="mt-5 text-slate-700 font-medium">{passed?`Congratulations! You scored ${correct}/${questions.length} and successfully cleared the examination.`:`You scored ${correct}/${questions.length}. A minimum score of ${PASSING_SCORE}/${questions.length} is required to clear the test.`}</p><div className="mx-auto mt-7 grid max-w-md grid-cols-2 gap-3 text-left"><Status good={passed}>{passed?'Candidate cleared the exam':'Candidate failed the test'}</Status><Status>Technical interruptions: {session?.events.length??0}</Status></div><p className="mt-6 text-sm text-slate-500">Demo result — not an official government licence decision.</p><button onClick={()=>navigate('/review')} className="btn-primary mt-6">View examination summary</button></div></main>}
if(path==='/review')return <main className="mx-auto max-w-2xl px-5 py-10"><div className="card p-7"><h1 className="text-3xl font-bold">Examination summary</h1><p className="mt-2">{candidate.name} · {candidate.application}</p><h2 className="mt-7 font-bold">Proctoring summary</h2><div className="mt-3 space-y-3"><Status>Camera connected</Status>{session?.events.map(e=><Status key={e.id} icon="⚠" good={false}>{e.type.replaceAll('_',' ')} — recovered safely</Status>)}{!session?.events.length&&<Status>No technical interruptions recorded</Status>}<Status>Completed successfully</Status></div><button onClick={async()=>{await clearSession();navigate('/')}} className="btn-secondary mt-7">Return to home</button></div></main>;
return <main className="p-10">Page not found</main>};return <Shell>{content()}</Shell>}
