'use client';
import { useEffect, useRef, useState } from 'react';
import { FaceLandmarker, FilesetResolver } from '@mediapipe/tasks-vision';

type Step='waiting'|'passed'|'failed';
const BLINKS_REQUIRED=5, SMILE_REQUIRED_MS=5000, INTERVAL_MS=100;
export default function PreExamVerification({onComplete}:{onComplete:()=>void}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream>(),landmarker=useRef<FaceLandmarker>(),frame=useRef<number>(),last=useRef(0),blinkOpen=useRef(true),blinks=useRef(0),smileStart=useRef(0); const [camera,setCamera]=useState<Step>('waiting'),[browser,setBrowser]=useState<Step>('waiting'),[face,setFace]=useState<Step>('waiting'),[blinkCount,setBlinkCount]=useState(0),[smileMs,setSmileMs]=useState(0),[message,setMessage]=useState('Preparing secure liveness verification.');
 const ready=camera==='passed'&&browser==='passed'&&face==='passed'&&blinkCount>=BLINKS_REQUIRED&&smileMs>=SMILE_REQUIRED_MS;
 useEffect(()=>{let alive=true;const init=async()=>{try{if(!navigator.mediaDevices?.getUserMedia){setBrowser('failed');setMessage('This browser does not support the required verification features.');return;}setBrowser('passed');stream.current=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480}},audio:true});if(!alive||!video.current)return;video.current.srcObject=stream.current;await video.current.play();setCamera('passed');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');landmarker.current=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'/models/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true});loop();}catch{setCamera('failed');setMessage('Camera or microphone access is required. Allow access and try again.');}};const loop=()=>{if(!alive||!video.current||!landmarker.current)return;const now=performance.now();if(now-last.current>=INTERVAL_MS&&video.current.readyState>=2){last.current=now;const result=landmarker.current.detectForVideo(video.current,now);const shapes=result.faceBlendshapes?.[0]?.categories??[];const score=(name:string)=>shapes.find(item=>item.categoryName===name)?.score??0;if(result.faceLandmarks?.length){setFace('passed');const closed=(score('eyeBlinkLeft')+score('eyeBlinkRight'))/2>.55;if(closed&&blinkOpen.current){blinkOpen.current=false;blinks.current+=1;setBlinkCount(blinks.current);}if(!closed)blinkOpen.current=true;const hasPassed=smileStart.current&&(Date.now()-smileStart.current>=SMILE_REQUIRED_MS);if(hasPassed){setSmileMs(SMILE_REQUIRED_MS);}else{const smiling=(score('mouthSmileLeft')+score('mouthSmileRight'))/2>.45;if(smiling){smileStart.current||=(Date.now());setSmileMs(Math.min(SMILE_REQUIRED_MS,Date.now()-smileStart.current));}else{smileStart.current=0;setSmileMs(0);}}}}frame.current=requestAnimationFrame(loop);};init();return()=>{alive=false;if(frame.current)cancelAnimationFrame(frame.current);landmarker.current?.close();stream.current?.getTracks().forEach(track=>track.stop());};},[]);
 const row=(label:string,state:Step,detail:string)=><div className={`flex items-center justify-between rounded-xl p-3 ${state==='passed'?'bg-emerald-50':state==='failed'?'bg-red-50':'bg-slate-50'}`}><span className="font-semibold">{label}</span><span className="text-sm">{state==='passed'?'✓':state==='failed'?'⚠':'…'} {detail}</span></div>;
 return <main className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-bold">Candidate verification</h1><p className="mt-2 text-slate-600">Complete this interactive liveness check before viewing the exam.</p><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="card overflow-hidden"><div className="aspect-video bg-slate-900"><video ref={video} autoPlay muted playsInline className="h-full w-full object-cover"/></div><p className="p-3 text-sm font-semibold">{message}</p></div><div className="card p-5"><h2 className="font-bold">Verification checklist</h2><div className="mt-4 space-y-3">{row('System & browser',browser,browser==='passed'?'Compatible':'Checking')}{row('Camera & microphone',camera,camera==='passed'?'Connected':'Checking')}{row('Face visible',face,face==='passed'?'Detected':'Look at the camera')}{row('Blink detection',blinkCount>=BLINKS_REQUIRED?'passed':'waiting',`${blinkCount} / ${BLINKS_REQUIRED} blinks`)}{row('Smile detection',smileMs>=SMILE_REQUIRED_MS?'passed':'waiting',smileMs>=SMILE_REQUIRED_MS?'Complete':`Smile continuously: ${Math.max(0,Math.ceil((SMILE_REQUIRED_MS-smileMs)/1000))}s`)}</div><button disabled={!ready} onClick={onComplete} className="btn-primary mt-6 w-full">Start Test</button><p className="mt-3 text-xs text-slate-500">Start Test stays disabled until every check passes.</p></div></div></main>;
}
