'use client';
import { useEffect, useRef, useState } from 'react';
import { FaceDetectionManager } from '@/features/proctoring/face/FaceDetectionManager';
import type { FaceResult, FaceSnapshot } from '@/features/proctoring/face/faceTypes';
import { FACE_CONFIG } from '@/features/proctoring/face/faceConfig';
import { AudioProctor } from '@/features/proctoring/audio/AudioProctor';
import { storeAudioChunk } from '@/features/proctoring/audio/audioEvidence';
import type { AudioEventType, AudioMetrics, AudioStatus } from '@/features/proctoring/audio/audioTypes';

type Props={sessionId:string;onMultipleFaces:(result:FaceResult)=>void;onMultipleFacesResolved:()=>void;onFaceMissing:(duration:number)=>void;onLookingAway:(duration:number)=>void;onSnapshot:(snapshot:FaceSnapshot)=>void;onDetectorError:()=>void;onAudioEvent:(type:AudioEventType,metrics?:AudioMetrics,duration?:number)=>void};
export default function ProctoredCamera({sessionId,onMultipleFaces,onMultipleFacesResolved,onFaceMissing,onLookingAway,onSnapshot,onDetectorError,onAudioEvent}:Props){
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream>(), manager=useRef<FaceDetectionManager>(), audio=useRef<AudioProctor>(), callbacks=useRef({onMultipleFaces,onMultipleFacesResolved,onFaceMissing,onLookingAway,onSnapshot,onDetectorError,onAudioEvent}); const [snapshot,setSnapshot]=useState<FaceSnapshot|null>(null);const [message,setMessage]=useState('Connecting camera…');const [audioStatus,setAudioStatus]=useState<AudioStatus>('STARTING'); callbacks.current={onMultipleFaces,onMultipleFacesResolved,onFaceMissing,onLookingAway,onSnapshot,onDetectorError,onAudioEvent};
 useEffect(()=>{let active=true;const start=async()=>{try{stream.current=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,min:15}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!active||!video.current)return;video.current.srcObject=stream.current;await video.current.play();audio.current=new AudioProctor({onEvent:(type,metrics,duration)=>callbacks.current.onAudioEvent(type,metrics,duration),onStatus:setAudioStatus,onChunk:(blob)=>void storeAudioChunk(sessionId,blob)});audio.current.start(stream.current);manager.current=new FaceDetectionManager({onUpdate:(next)=>{setSnapshot(next);callbacks.current.onSnapshot(next);},onMultipleFaces:(result)=>callbacks.current.onMultipleFaces(result),onMultipleFacesResolved:()=>callbacks.current.onMultipleFacesResolved(),onNoFace:(duration)=>callbacks.current.onFaceMissing(duration),onLookingAway:(duration)=>callbacks.current.onLookingAway(duration),onError:()=>{setMessage('Face monitoring could not be started.');callbacks.current.onDetectorError();}});await manager.current.start(video.current);if(active)setMessage('Camera and face monitoring active');}catch{setMessage('Camera or microphone access is blocked. Allow access and try again.');callbacks.current.onDetectorError();}};start();return()=>{active=false;manager.current?.stop();audio.current?.stop();stream.current?.getTracks().forEach(track=>track.stop());};},[sessionId]);
 const simulate=(count:number)=>manager.current?.simulate(count); return <div className="card overflow-hidden"><div className="relative aspect-video bg-slate-900"><video ref={video} autoPlay muted playsInline className="h-full w-full object-cover"/>{process.env.NODE_ENV!=='production'&&snapshot?.faces.map((face,i)=><div key={i} className="absolute border-2 border-lime-400" style={{left:`${face.xMin*100}%`,top:`${face.yMin*100}%`,width:`${face.width*100}%`,height:`${face.height*100}%`}}><span className="bg-lime-400 px-1 text-xs text-slate-950">Face {i+1}</span></div>)}</div><div className="p-3"><p className="text-sm font-semibold">{message}</p><p className="mt-1 text-xs font-bold">Microphone: {audioStatus.replace('_',' ').toLowerCase()}</p>{process.env.NODE_ENV!=='production'&&<><div className="mt-3 rounded bg-slate-900 p-3 font-mono text-xs text-white"><b>FACE PROCTOR DEBUG</b><br/>Detector: {FACE_CONFIG.model}<br/>Video: {video.current?.videoWidth||0} × {video.current?.videoHeight||0}<br/>Face count: {snapshot?.faceCount??'—'} · {snapshot?.fps.toFixed(1)??'—'} FPS<br/>Head: {snapshot?.headDirection??'STARTING'}<br/>Audio: {audioStatus}</div><div className="mt-3 grid grid-cols-2 gap-2">{[0,1,2].map(n=><button key={n} onClick={()=>simulate(n)} className="rounded border px-2 py-1 text-xs font-bold">Simulate {n} faces</button>)}</div><button onClick={()=>manager.current?.simulate(undefined)} className="mt-2 text-xs font-bold text-blue-700">Use live detector</button></>}</div></div>;
}
