export type AudioEventType='AUDIO_ACTIVITY'|'SPEECH_DETECTED'|'SUSTAINED_SPEECH'|'REPEATED_SPEECH'|'MICROPHONE_DISCONNECTED'|'MICROPHONE_PERMISSION_LOST'|'AUDIO_TRACK_MUTED'|'AUDIO_TRACK_ENDED'|'AUDIO_RECORDING_FAILED';
export type AudioMetrics={rms:number;peak:number;noiseFloor:number;zeroCrossings:number};
export type AudioStatus='STARTING'|'MONITORING'|'SILENCE'|'BACKGROUND_NOISE'|'SPEECH_LIKE'|'ERROR';
