import { AUDIO_CONFIG } from './audioConfig';
import type { AudioEventType, AudioMetrics, AudioStatus } from './audioTypes';

type Callbacks={onEvent:(type:AudioEventType,metrics?:AudioMetrics,duration?:number)=>void;onStatus:(status:AudioStatus)=>void;onChunk:(blob:Blob)=>void};
/** Uses a supplied stream only. It neither opens nor uploads microphone audio. */
export class AudioProctor {
 private context:AudioContext|undefined;private analyser:AnalyserNode|undefined;private data:Float32Array|undefined;private recorder:MediaRecorder|undefined;private timer:number|undefined;private track:MediaStreamTrack|undefined;private running=false;private activeSince=0;private speechSince=0;private lastActivity=0;private lastSpeech=0;private lastSpeechDetected=0;private speechEvents:number[]=[];private noiseFloor=0.006;
 constructor(private callbacks:Callbacks){}
 start(stream:MediaStream){this.stop();const track=stream.getAudioTracks()[0];if(!track){this.callbacks.onEvent('MICROPHONE_DISCONNECTED');this.callbacks.onStatus('ERROR');return;}try{this.running=true;this.track=track;this.context=new AudioContext();void this.context.resume();const audioOnly=new MediaStream([track]);const source=this.context.createMediaStreamSource(audioOnly);this.analyser=this.context.createAnalyser();this.analyser.fftSize=AUDIO_CONFIG.fftSize;this.data=new Float32Array(this.analyser.fftSize);source.connect(this.analyser);this.listen(track);this.startRecorder(audioOnly);this.callbacks.onStatus('MONITORING');this.sample();}catch{this.fail('MICROPHONE_PERMISSION_LOST');}}
 stop(){this.running=false;if(this.timer)window.clearTimeout(this.timer);this.timer=undefined;this.track?.removeEventListener('ended',this.ended);this.track?.removeEventListener('mute',this.muted);this.track?.removeEventListener('unmute',this.unmuted);if(this.recorder&&this.recorder.state!=='inactive')this.recorder.stop();this.recorder=undefined;this.context?.close().catch(()=>undefined);this.context=undefined;this.analyser=undefined;}
 private listen(track:MediaStreamTrack){track.addEventListener('ended',this.ended);track.addEventListener('mute',this.muted);track.addEventListener('unmute',this.unmuted);}
 private ended=()=>this.fail('AUDIO_TRACK_ENDED'); private muted=()=>{this.callbacks.onEvent('AUDIO_TRACK_MUTED');this.callbacks.onStatus('ERROR');};private unmuted=()=>this.callbacks.onStatus('MONITORING');
 private startRecorder(stream:MediaStream){if(!window.MediaRecorder)return this.callbacks.onEvent('AUDIO_RECORDING_FAILED');const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type));try{this.recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);this.recorder.addEventListener('dataavailable',event=>{if(event.data.size)this.callbacks.onChunk(event.data);});this.recorder.addEventListener('error',()=>this.callbacks.onEvent('AUDIO_RECORDING_FAILED'));this.recorder.addEventListener('stop',()=>{if(this.running)this.callbacks.onEvent('AUDIO_RECORDING_FAILED');});this.recorder.start(AUDIO_CONFIG.recordingChunkMs);}catch{this.callbacks.onEvent('AUDIO_RECORDING_FAILED');}}
 private sample(){if(!this.running||!this.analyser||!this.data)return;if(!this.track||!this.track.enabled){this.fail('MICROPHONE_DISCONNECTED');return;}this.analyser.getFloatTimeDomainData(this.data);let sum=0,peak=0,crossings=0,last=this.data[0];for(let i=0;i<this.data.length;i++){const value=this.data[i];sum+=value*value;peak=Math.max(peak,Math.abs(value));if((value>=0)!==(last>=0))crossings++;last=value;}const rms=Math.sqrt(sum/this.data.length);const metrics={rms,peak,noiseFloor:this.noiseFloor,zeroCrossings:crossings};const threshold=Math.max(AUDIO_CONFIG.minimumRms,this.noiseFloor*AUDIO_CONFIG.noiseMultiplier);const active=rms>threshold;const speechLike=active&&crossings>8&&crossings<280;const now=Date.now();if(!active){this.noiseFloor=this.noiseFloor*.97+rms*.03;this.activeSince=0;this.speechSince=0;this.callbacks.onStatus(rms>this.noiseFloor?'BACKGROUND_NOISE':'SILENCE');}else{this.activeSince||=(now);if(now-this.lastActivity>AUDIO_CONFIG.activityCooldownMs){this.lastActivity=now;this.callbacks.onEvent('AUDIO_ACTIVITY',metrics,now-this.activeSince);}if(speechLike){this.speechSince||=(now);this.callbacks.onStatus('SPEECH_LIKE');if(now-this.speechSince>=AUDIO_CONFIG.speechDetectionMs&&now-this.lastSpeechDetected>AUDIO_CONFIG.speechCooldownMs){this.lastSpeechDetected=now;this.callbacks.onEvent('SPEECH_DETECTED',metrics,now-this.speechSince);}if(now-this.speechSince>=AUDIO_CONFIG.sustainedSpeechMs&&now-this.lastSpeech>AUDIO_CONFIG.speechCooldownMs){this.lastSpeech=now;this.speechEvents=this.speechEvents.filter(time=>now-time<AUDIO_CONFIG.repeatWindowMs);this.speechEvents.push(now);this.callbacks.onEvent('SUSTAINED_SPEECH',metrics,now-this.speechSince);if(this.speechEvents.length>=2)this.callbacks.onEvent('REPEATED_SPEECH',metrics,now-this.speechSince);}}else{this.speechSince=0;this.callbacks.onStatus('BACKGROUND_NOISE');}}this.timer=window.setTimeout(()=>this.sample(),AUDIO_CONFIG.analysisIntervalMs);}
 private fail(type:AudioEventType){this.callbacks.onEvent(type);this.callbacks.onStatus('ERROR');this.stop();}
}
